# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('oaid', models.BigIntegerField(default=0)),
                ('fromuid', models.BigIntegerField(default=0)),
                ('appid', models.BigIntegerField(default=0)),
                ('msgid', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('mac', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
    ]
