# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhook',
            options={'verbose_name': 'WebHook'},
        ),
        migrations.AlterField(
            model_name='webhook',
            name='appid',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
