# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_auto_20171216_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='message',
            field=models.TextField(),
        ),
    ]
