# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respond', models.CharField(blank=True, max_length=1000)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_hook', to='webhook.WebHook')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
